<h1>Nouveau Meetup</h1>
<?php
    $form = $this->form; 
    echo $this->form()->openTag($form); 
?>

<div class="row">
    <div class='col-sm-6- col-md-6'>
        <?= $this->formRow($form->get('title')) ?>
    </div>
</div>

<div class="row">
    <div class='col-sm-6 col-md-6'>
        <?= $this->formRow($form->get('description')) ?>
    </div>
</div> 

<div class="row">
    <div class='col-sm-6 col-md-6'>

        <?php echo $this->formRow($form->get('dateBegin')) ?>

        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
</div>

<div class="row">
    <div class='col-sm-6 col-md-6'>
        <?php echo $this->formRow($form->get('dateEnd')) ?>
        <span class="input-group-addon">
            <span class="glyphicon glyphicon-calendar"></span>
        </span>
    </div>
</div>

<?php echo $this->formInput($form->get('submit')) ?>
<br>
<?php echo $this->form()->closeTag($form); ?>

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
            $('#datetimepicker2').datetimepicker();
        });
    </script>
